export GOPATH=$PROJECTS
export LSCOLORS="exfxcxdxbxegedabagacad"
export CLICOLOR=true
export EDITOR=nvim
export LICENSE_FULL_NAME="Ben Burwell"
export WWW_HOME="https://news.ycombinator.com/"
export LYNX_LSS="$HOME/.lynx.lss"
export LYNX_CFG="$HOME/.lynx.cfg"
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow -g "!{.git,node_modules}/*" 2> /dev/null'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export BROWSER="Firefox"
export NVM_DIR="$HOME/.nvm"
