[Colors]
FG = "0xbdbaae"
BG = "0x222222"
Cursor = "0xbbbbbb"
CursorText = "0x15171c"
Bold = "0xffffff"
Highlight = "0x272e35"
HighlightText = "0xffffff"
Black = "0x15171c"
BrightBlack = "0x555555"
Red = "0xec5f67"
BrightRed = "0xff6973"
Green = "0x81a764"
BrightGreen = "0x93d493"
Yellow = "0xfec254"
BrightYellow = "0xffd256"
Blue = "0x5486c0"
BrightBlue = "0x4d84d1"
Magenta = "0xbf83c1"
BrightMagenta = "0xff55ff"
Cyan = "0x57c2c1"
BrightCyan = "0x83e9e4"
White = "0xefece7"
BrightWhite = "0xffffff"

[ZSH]
AutoScripts = [
  "/usr/local/opt/fzf/shell/completion.zsh",
  "/usr/local/opt/fzf/shell/key-bindings.zsh",
  "$HOME/.iterm2_shell_integration.zsh",
  "$HOME/.travis/travis.sh",
  "$HOME/.rvm/scripts/rvm",
  "$HOME/Applications/google-cloud-sdk/path.zsh.inc",
  "$HOME/Applications/google-cloud-sdk/completion.zsh.inc"
]
