[Colors]
FG = "0xe6e0cf"
BG = "0x0e2133"
Cursor = "0xdf1717"
Bold = "0xffffff"
Highlight = "0x00374b"
HighlightText = "0xfeffff"
Black = "0x151c23"
BrightBlack = "0x5c7b99"
Red = "0xdf6a6a"
BrightRed = "0xff8c8c"
Green = "0x99b34f"
BrightGreen = "0xbadc5b"
Yellow = "0xdfb46a"
BrightYellow = "0xf7cd86"
Blue = "0x7390bf"
BrightBlue = "0x9dbdf1"
Magenta = "0x9f6eeb"
BrightMagenta = "0xb593e6"
Cyan = "0x73b8bf"
BrightCyan = "0x95dfe6"
White = "0xe6e0cf"
BrightWhite = "0xfff9e9"

[ZSH]
AutoScripts = [
  "/usr/local/opt/fzf/shell/completion.zsh",
  "/usr/local/opt/fzf/shell/key-bindings.zsh",
  "$HOME/.iterm2_shell_integration.zsh",
  "$HOME/.travis/travis.sh",
  "$HOME/.rvm/scripts/rvm",
  "$HOME/Applications/google-cloud-sdk/path.zsh.inc",
  "$HOME/Applications/google-cloud-sdk/completion.zsh.inc"
]
