export PROJECTS=~/code
export VIRTYX_DIR="$PROJECTS/src/github.com/virtyx-technologies"
export PASSWORD_STORE_GENERATED_LENGTH=64
export GOPATH="$PROJECTS"
export LSCOLORS="exfxcxdxbxegedabagacad"
export CLICOLOR=true
export EDITOR=nvim
export LICENSE_FULL_NAME="Ben Burwell"
export WWW_HOME="https://duckduckgo.com/"
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow -g "!{.git,node_modules}/*" 2> /dev/null'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export NVM_DIR="$HOME/.nvm"
export CDPATH=$HOME/c:$HOME
export SSLKEYLOGFILE="$HOME/.mitmproxy/sslkeylogfile.txt"
export BAT_PAGER="less -rf"
export CONF_SOURCE="$HOME/c/dotfiles"
