#!/usr/bin/osascript

tell application "Alacritty"
	tell application "System Events" to tell process "Alacritty"
		if front window exists then
			tell front window
        set value of attribute "AXFullScreen" to true
			end tell
		end if
	end tell
end tell
